<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>preview</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFrameworks>net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
    </PropertyGroup>
    <ItemGroup>
        <None Include="../LICENSE" Pack="true" PackagePath=""/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Undefined.Events" Version="1.0.4"/>
        <PackageReference Include="Undefined.IsExternalInit" Version="1.0.0"/>
        <PackageReference Include="Undefined.Verify" Version="2.0.0"/>
    </ItemGroup>
</Project>
